# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'asiloSOS' do

  use_frameworks!
  pod 'Firebase/Core'
  pod 'RevealingSplashView'
  pod 'LBTAComponents'
  pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'
  pod 'FAQView', '~> 0.5.0'

end
