# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'asiloSOS' do

  use_frameworks!
  pod 'Firebase/Core'
  pod 'RevealingSplashView'
  pod 'LBTAComponents'

end
