# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'asiloSOS' do

  use_frameworks!
  pod 'FAQView'
  pod 'Firebase/Core'
  pod 'Firebase/Auth’
  pod 'Firebase/Database'
  pod 'RevealingSplashView'
  pod 'LBTAComponents'
  pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'

end
